baseURL = "https://ishaanbhimwal.github.io"
theme = "risotto"
title = "ISHAAN BHIMWAL"
author = "Ishaan Bhimwal"
copyright = "© 2023 ishaanbhimwal"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "ishaanbhimwal"
#description = "A [hugo](https://gohugo.io) theme inspired by terminal ricing."
#logo = "images/ishaanbhimwal.jpg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/ishaanbhimwal"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:ishaanbhimwal@protonmail.com"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/ishaanbhimwal"

[[params.socialLinks]]
icon = "fa-solid fa-file"
title = "Resume"
url = "https://drive.google.com/file/d/1fr7du_1OM2PMnW-LUCw8MzHwO58ccvsa/view?usp=sharing"

[menu]

  [[menu.main]]
    identifier = "whoami"
    name = "Whoami"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "other"
    name = "Other"
    url = "/other/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
